name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pandoc/latex:edge-ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake and make
        run: |
          apt-get update
          apt-get install -y cmake make

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build PDF files
        run: cmake --build build
